### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HideakiAtsuyo** [KjSux/Katarino-Sniper#1]
Utiliser la source de base au lieu d'un code protégé par pyarmor qui peut être infecté :)

[ICI](https://github.com/Alucard-Selfbot/Alucard-Selfbot-src)

**Comment by KjSux** [comment]
Un peux vrai mais bon si tu pense qu'il est infecté tu veux que je te dise quoi de plus :)

**Comment by HideakiAtsuyo** [comment]
> Un peux vrai mais bon si tu pense qu'il est infecté tu veux que je te dise quoi de plus :)

En même temps qu'est-ce qu'un attardé peut faire d'autre sachant que ce n'est même pas ton code :)

**Comment by KjSux** [comment]
> > Un peux vrai mais bon si tu pense qu'il est infecté tu veux que je te dise quoi de plus :)
> 
> En même temps qu'est-ce qu'un attardé peut faire d'autre sachant que ce n'est même pas ton code :)

N'ajoute pas le mot attardé reste chill est non je n'est jamais pensé a ajouté un code infecté je suis pas de ce genre la tu peux vérifier par toi meme en checkant les requetes sur ce je close la suggestion est n'en n'ajoute pas plus.
